### ISSUE TITLE
how to use nanoseconds ?

### ISSUE THREAD

**Issue by Ha2ryZhang** [rnd-debug/log4js-influxdb-appender#2]
```
> select * from log
name: log
time                cheese    quantity scientist
----                ------    -------- ---------
1599722773500000000 roquefort 100      Marie Curie
1599722927792000000 roquefort 233      Marie Curie
```

**Comment by rnd-debug** [comment]
@Ha2ryZhang  Hello. Can you be more precise? What is exactly your question?
Per default, `log4js` produces timestamps up to millisecond, as per native Javascript. Do you want it to be able to produce timestamps in nanoseconds?
Or is your question related to InfluxDB?

**Comment by Ha2ryZhang** [comment]
@rnd-debug 
Is when the concurrency is high, there will be data loss，
```
  function processLogEvent(loggingEvent) {
    const measurement = configMeasurement || getMeasurement('categoryName', loggingEvent);

    const fields = parseLogEvent(loggingEvent, configFields);
    const tags = parseLogEvent(loggingEvent, configTags);
    return {
      measurement,
      timestamp: loggingEvent.startTime, // here 
      tags,
      fields,
    };
  }
```
the influxdb primary key is timestamp + tag ,The same data will be overwritten

Can the time stamp be changed to nanoscends Or any other way

**Comment by rnd-debug** [comment]
Understood. Several ideas:
- **log4js** returning a timestamp in nanoseconds: will involve to add additional dependencies to it (based on ` process.hrtime()` or on `performance.now()` or some other mechanism), that will depend on whether it is run in browser or on server. => you can ask a question on their git.
- **log4js-influxdb** using a field specified by user as timestamp => I have to check what is possible here.
- **log4js-influxdb** using an additional dependecy to created nanosecond-timestamp if requested by user => I have to check what is possible here.
- you can also manually build a "nanosecond" variable so that data will be different.  Check this: https://docs.influxdata.com/influxdb/v2.0/write-data/best-practices/duplicate-points/

There were issues opened on **node-influx** for the overwrite topic:
- https://github.com/node-influx/node-influx/issues/297

**Comment by Ha2ryZhang** [comment]
@rnd-debug i use an additional dependecy to created nanosecond-timestamp But it still lost data, and I finally figured out why.
```
function write() {
    canWrite = false;
    client
      .writePoints(buffer.map((logEvent) => processLogEvent(logEvent)))
      .then(() => {  // I don’t think we need to wait here
        buffer = [];
        canWrite = true;
      })
      .catch((err) => {
        console.error(err);
      });
  }
```
i changed to 
```
 if (canWrite && shouldWriteBatch()) {
    canWrite = false;
    client
    .writePoints(buffer.map((logEvent) => processLogEvent(logEvent)))
    .catch((err) => {
      console.error(err);
    });
    buffer = [];
    canWrite = true;
  }
```
it is work
I wrote a test to prove that I don’t know if it’s right
```
//maxBatchSize = 1000;
for (let index = 0; index < 10000; index++) {
    //I changed it here, log4js was not used
    logger.info({
      measurement: 'test',
      tags: { host: '1' },
      fields: {
        name: 'name',
        age: num++,
      },
      timestamp: now(),
    });
  }

result :
> select count(*) from test
name: test
time count_age count_name
---- --------- ----------
0    1000      1000
```
I don’t think there should be waiting for a successful write to reset the `buffer`。
Suppose I have not finished writing, but the length of the buffer is greater than maxBatchSize, but the buffer is reset。

**Comment by rnd-debug** [comment]
I think you are right. I pushed an update for the `buffer = []`.
